git

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,7 +1,17 @@
 #!/usr/bin/env bash
-# Installs Nginx
+# Script to install and configure Nginx on Ubuntu server to serve "Hello World!" on port 80
 
-apt-get update
-apt-get install -y nginx
-echo "Holberton School" > /var/www/html/index.html
+# Exit immediately if a command exits with a non-zero status
+set -e
+
+# Update package lists
+apt-get update -y
+
+# Install Nginx
+apt-get install nginx -y
+
+# Replace the default Nginx index.html with a custom one containing "Hello World!"
+echo "Hello World!" > /var/www/html/index.nginx-debian.html
+
+# Start Nginx
 service nginx start
